### ISSUE TITLE
Considering the Century

### ISSUE THREAD

**Issue by Kinjalrk2k** [Calendar-Application/Calendar-2#1]
https://github.com/Calendar-Application/Calendar-2/blob/26099cb856ec5624999056fe8c75475c515b9e6c/main.c#L31

is it essential to add all the years from 1AD?
cant we just add from the lower year?
@Somsubhra1

**Comment by Somsubhra1** [comment]
We can do it. But then we need to check which year is lesser in dayDifference() and pass that year to day_Number() as a parameter.
